#!/usr/bin/env bash
# This script transfers a file from our client to a server using scp

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Use scp to transfer the file
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "File transfer failed"
fi
