#!/usr/bin/env bash
# Configures Nginx server with custom 404 page

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Create custom 404 page
echo "<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>" > /var/www/html/custom_404.html

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart01~
